### ISSUE TITLE
MP - Tagging external cross-references

### ISSUE THREAD

**Issue by droyyyy** [justicecanada/lims-xml-dtd#10]
Advised Leg wg it is ready for testing (2022-01-19)

Guy gave demo using it and WG is very pleased with changes. 
They will respond with a small bug they found along with a suggestion. (2022-03-02)

F12,Q does not work on a selected number, F12,N does so both should work the same. ** (JS)**
Fixed that issue in DEV in PREPROD **(MA)**
F12,Q works on a selected number now but the scoot doesnt insert the number it inserts just the ID. **(JS)**
Should work now (MA) - Tested in DEV and PREPROD both tested ok **(JS)**

[Cross-references (1).docx](https://github.com/justicecanada/lims-xml-dtd/files/8682149/Cross-references.1.docx)

**Comment by apressey** [comment]
A new element will be created called XRefSection to support this feature.  This will avoid having to write exceptions in the code to avoid issues with styling XRefExternals.

**Comment by malijagi** [comment]
I made changes to work with a new tag XRefSection.
It is ready for testing in DEV

**Comment by staffj** [comment]
- F12,Q inserts XRefSection and includes lawid and number as expected. 

- XRefSection needs to be added to the J-Mark menu
 ![image](https://user-images.githubusercontent.com/104795275/183102700-4e2f779f-10f2-4baf-b356-534a3a0a05e1.png)

- When selecting the number, pressing enter and selecting XRefSection, only the tag is inserted. Should the form pop up?

- Renumbering macro did not renumber them.
