### ISSUE TITLE
Bill Exchange - add title to ImageGroup

### ISSUE THREAD

**Issue by apressey** [justicecanada/lims-xml-dtd#16]
To sync with Regulations for possible 2 part Image headers.  Follow the same font size and style as Tables.

**Comment by apressey** [comment]
Changing this content model to better support backwards compatibility and also to make it consistent with the Table model, where Caption element is placed before title.

**Comment by staffj** [comment]
Existing files with an ImageGroup are opening Out of Context due to placement change of Caption.
