### ISSUE TITLE
CIF and CIFnobold French alias EEV and EEVnongras

### ISSUE THREAD

**Issue by malijagi** [justicecanada/lims-xml-dtd#26]

**Comment by malijagi** [comment]
In TEST

**Comment by staffj** [comment]
Tested ok. Ready for Preprod

**Comment by malijagi** [comment]
Copied to PROD

**Comment by staffj** [comment]
WG would like CIF text colour, regular and bold, to be changed to the same colour used in Summary

![image](https://user-images.githubusercontent.com/104795275/186509752-7b668e4f-e7dc-4603-bc2c-aa742c3523a3.png)

**Comment by staffj** [comment]
Checked DEV first but change is not there. Change is in Preprod and it looks good.

**Comment by malijagi** [comment]
OK, I put it in DEV zip.
