### ISSUE TITLE
TC Security Measures template update

### ISSUE THREAD

**Issue by malijagi** [justicecanada/lims-xml-dtd#27]
Update to TC SM templates found in M:\Test\Issues\lims-arbortext-custom\TC Security Measures template update to be included in upcoming September release.

Moved from https://github.com/justicecanada/lims-arbortext-custom/issues/27

**Comment by malijagi** [comment]
Do we need to remove Comments in templates?

**Comment by staffj** [comment]
No, they should be left as this is what they asked for. They are further instructions for the drafter when creating an SM.

**Comment by malijagi** [comment]
In DEV and PREPROD

**Comment by droyyyy** [comment]
After having created my own TC Security Measures file, used the compare feature to compare with the TCSM templates on M:, I can confirm that they are identical.
This test produced the same results for ENG and FR files in both DEV and PREPROD
