### ISSUE TITLE
Statute DTD - CIFnobold

### ISSUE THREAD

**Issue by staffj** [justicecanada/lims-xml-dtd#30]
Using the Epic link in Folio to open a file produces an invalid attribute for CIFnobold message as Statute DTD needs to be updated.

**Comment by droyyyy** [comment]
Tested in DEV and the CIFnobold is now recognized by the Statutes DTD.
Looks good.

**Comment by staffj** [comment]
Ready for preprod

**Comment by malijagi** [comment]
Moved to PREPROD

**Comment by droyyyy** [comment]
CIFnobold is recognized and looks good in PREPROD for both ENG and FRE environments.
