### ISSUE TITLE
XRefExternal attributes for IBR

### ISSUE THREAD

**Issue by staffj** [justicecanada/lims-xml-dtd#46]
Please remove the IBR attributes that are on the XRefExternal tag in Regs DTD:

**Comment by malijagi** [comment]
Can we move this issue to PREPROD?

**Comment by staffj** [comment]
Not yet as I need to give a heads up to HoC and CG still.

**Comment by malijagi** [comment]
It is just for Regs, we removed attributes

**Comment by apressey** [comment]
I am going to combine this with issue #43
