### ISSUE TITLE
Bills template - change to regnal year effective September 8

### ISSUE THREAD

**Issue by sgorn** [justicecanada/lims-xml-dtd#56]
- [x] Add "-3" to eng and fre bill templates effective **September 8**
![image](https://github.com/user-attachments/assets/4bc8d88a-e979-406e-85d4-c273cf0bf64e)

![image](https://github.com/user-attachments/assets/4b454f79-7e35-42f6-a19b-9f9e8e976ca1)

References: https://github.com/justicecanada/lims-arbortext-custom/issues/226

**Comment by staffj** [comment]
Change looks good in test.
While testing I realized that the J-Action, Update DTD macro needs to be updated as well and I will open an issue for it.

**Comment by sgorn** [comment]
Updated in Test:

Regnal year change in English and French
