### ISSUE TITLE
Smart block and paste of a comment block under a definition

### ISSUE THREAD

**Issue by droyyyy** [justicecanada/lims-xml-dtd#8]
Email from User: Are you able to copy a comment block under a definition and paste it under another definition. Neither my coworker or I can. But it works for a copied block under a section/subsection that is pasted under another section/subsection. There is no reason why the paste shouldn't work for definitions.

AP - When I paste a Comment Block at the end of a definition, it always goes above.  Its interesting paste behavior.

**Comment by staffj** [comment]
The paste behavior is definitely weird but if your cursor is after /Text tag, it pastes ok. I tried with my cursor in the Definition text and it inserted the yellow _comment so I deleted it, put my cursor after \Text and pasted. I then put my cursor back in the text and it then pasted ok.

Does anything further need to be done here?

**Comment by staffj** [comment]
This issue has been reported again. Cannot paste a commentblock at the end of the defintion, it pastes as a yellow comment.
![image](https://user-images.githubusercontent.com/104795275/200347194-8316de62-4648-47eb-8f27-871f00e0f3d2.png)

**Comment by malijagi** [comment]
https://github.com/justicecanada/lims-arbortext-custom/issues/100
