### ISSUE TITLE
AmendedText - allow Table Title

### ISSUE THREAD

**Issue by droyyyy** [justicecanada/lims-xml-dtd#9]
Allow the title tag in Table in AmendedText.

It may need to be wrapped in Schedule tag so that the PT will use the proper font

**Comment by apressey** [comment]
Yes this is true.  The look of the <title> element changes depending on whether it is in a Schedule or not.   So the wrapper is need in order to have the proper look, otherwise a new attribute would be needed, and I dont like that idea much.

**Comment by apressey** [comment]
Turns out the title element already has a format-ref attribute that will allowing styling in the absence of the proper wrapper.  This will mean a lot less change than trying to allow different wrappers inside of the AmendedText, since the table model requires a certain amount of tagging.
